// Python FSE/Deepskilling/Week 4/Module2_FrontendDev/handson_07/student-portal-angular/src/app/course-card/course-card.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-course-card',
  imports: [],
  templateUrl: './course-card.html',
  styleUrl: './course-card.css'
})
export class CourseCard {
  @Input() name = '';
  @Input() code = '';
  @Input() credits = 0;
  @Input() grade = '';
}

// Python FSE/Deepskilling/Week 3/Module2_FrontendDev/BalajiA/handson_05/student-portal-react/src/components/CourseCard.jsx
function CourseCard({ id, name, code, credits, grade, onEnroll }) {
  return (
    <article className="course-card">
      <h3>{name}</h3>
      <p>{code}</p>
      <span>{credits} credits</span>
      <p>Grade: {grade}</p>
      <button onClick={() => onEnroll(id)}>Enroll</button>
    </article>
  );
}

export default CourseCard;
