// Python FSE/Deepskilling/Week 4/Module2_FrontendDev/handson_08/student-portal-vue/src/components/Header.vue
<template>
  <header class="header">
    <div class="site-name">Student Portal</div>
    <nav>
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/courses">Courses</RouterLink>
      <RouterLink to="/profile">Profile</RouterLink>
    </nav>
    <div class="enrolled-count">Enrolled: {{ store.enrolledCourses.length }}</div>
  </header>
</template>

<script setup>
import { useEnrollmentStore } from '../stores/enrollment';

const store = useEnrollmentStore();
</script>

<style scoped>
.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 24px;
  background-color: #2c3e50;
  color: #fff;
}
.header nav a {
  color: #fff;
  text-decoration: none;
  margin-right: 16px;
}
</style>

// Python FSE/Deepskilling/Week 4/Module2_FrontendDev/handson_10/student-portal-react/src/components/Header.jsx
import { Link } from 'react-router-dom';
import { useSelector } from 'react-redux';

function Header() {
  const enrolledCourses = useSelector(state => state.enrollment.enrolledCourses);

  return (
    <header className="header">
      <div className="site-name">Student Portal</div>
      <nav>
        <ul>
          <li><Link to="/">Home</Link></li>
          <li><Link to="/courses">Courses</Link></li>
          <li><Link to="/profile">Profile</Link></li>
        </ul>
      </nav>
      <div className="enrolled-count">Enrolled: {enrolledCourses.length}</div>
    </header>
  );
}

export default Header;
